### ISSUE TITLE
Sonarr support?

### ISSUE THREAD

**Issue by kamilmirza** [mariotacke/radarr-ombi-sync#4]
can it be used with Sonarr instead of Radarr?

**Comment by mariotacke** [comment]
Can you tell me more about your use case? I found that Sonarr imports files properly; the motivation behind this project was the fact that Radarr works oddly with the Drone factory.

In simple terms, what would you like to achieve with a "sonarr-ombi-sync"?

**Comment by kamilmirza** [comment]
well my use-case would be to un-monitor downloaded episode
is it necessary to use ombi with it?

**Comment by mariotacke** [comment]
I believe Sonarr let's you set up monitoring profiles, so once an episode was found matching the profile, it won't search for it anymore. You can try to limit your Sonarr monitor to be more narrow (720p only for example), to avoid looking for 1080p releases. The reason this project uses Ombi is to check availability on the associated Plex Media Server via its API.
